### ISSUE TITLE
The program instantly quits on Windows 11

### ISSUE THREAD

**Issue by zhenlige** [Ralith/hypermine#435]

**Comment by patowen** [comment]
I'm not convinced that the problem applies to all Windows 11 machines, so more information is needed to debug your issue. Try running it with a command prompt so that you can see what the error message is that's closing the game.

Please include the error message in this bug report. Your Windows username will likely show up, so if you don't want that revealed, be sure to redact it before showing the error message.

I would also suggest looking at the troubleshooting tips at <https://github.com/Ralith/hypermine/wiki/Installation-instructions-for-Windows-10#thread-main-panics-immediately-upon-running>.
